import type { Metadata } from "next";
import "@fontsource/plus-jakarta-sans";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className="font-plus-jakarta-sans antialiased bg-white text-black min-h-screen"
        style={{ fontFamily: '"Plus Jakarta Sans Variable", sans-serif' }}
      >
        <div className="container mx-auto px-4 sm:px-6 lg:px-8 flex flex-col min-h-screen">
          {children}
        </div>
      </body>
    </html>
  );
}
